// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeZone.Modules.Incident.Core.DAL;

#nullable disable

namespace SafeZone.Modules.Incident.Core.DAL.Migrations
{
    [DbContext(typeof(IncidentDbContext))]
    [Migration("20260304014536_CreateIncidents")]
    partial class CreateIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("incidents")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("Incidents", "incidents");
                });

            modelBuilder.Entity("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentEntity", b =>
                {
                    b.OwnsOne("SafeZone.Modules.Incident.Core.Domain.ValueObjects.IncidentDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("IncidentEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("IncidentEntityId");

                            b1.ToTable("Incidents", "incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentEntityId");
                        });

                    b.OwnsOne("SafeZone.Modules.Incident.Core.Domain.ValueObjects.IncidentLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("IncidentEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExtraDetails")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("LocationDetails");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("IncidentEntityId");

                            b1.ToTable("Incidents", "incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentEntityId");
                        });

                    b.OwnsOne("SafeZone.Modules.Incident.Core.Domain.ValueObjects.IncidentSubject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("IncidentEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Subject");

                            b1.HasKey("IncidentEntityId");

                            b1.ToTable("Incidents", "incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentEntityId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Subject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
