// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeZone.Modules.Incident.Core.DAL;

#nullable disable

namespace SafeZone.Modules.Incident.Core.Data.Migrations
{
    [DbContext(typeof(IncidentDbContext))]
    [Migration("20260407164904_ChangeCategoryType")]
    partial class ChangeCategoryType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("incidents")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Incidents", "incidents");
                });

            modelBuilder.Entity("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IncidentUsers", "incidents");
                });

            modelBuilder.Entity("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentEntity", b =>
                {
                    b.HasOne("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SafeZone.Modules.Incident.Core.Domain.Entities.IncidentUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SafeZone.Modules.Incident.Core.Domain.ValueObjects.IncidentDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("IncidentEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("IncidentEntityId");

                            b1.ToTable("Incidents", "incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentEntityId");
                        });

                    b.OwnsOne("SafeZone.Modules.Incident.Core.Domain.ValueObjects.IncidentLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("IncidentEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ExtraDetails")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("LocationDetails");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.HasKey("IncidentEntityId");

                            b1.ToTable("Incidents", "incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentEntityId");
                        });

                    b.OwnsOne("SafeZone.Modules.Incident.Core.Domain.ValueObjects.IncidentSubject", "Subject", b1 =>
                        {
                            b1.Property<Guid>("IncidentEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Subject");

                            b1.HasKey("IncidentEntityId");

                            b1.ToTable("Incidents", "incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentEntityId");
                        });

                    b.Navigation("AssignedTo");

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Reporter");

                    b.Navigation("Subject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
