<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>87cbffdb-b88f-4f3c-8366-e3eaede95076</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SafeZone.Shared.Infrastructure\SafeZone.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Activity\SafeZone.Modules.Activity.Api\SafeZone.Modules.Activity.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\SafeZone.Modules.Identity.Api\SafeZone.Modules.Identity.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Incident\SafeZone.Modules.Incident.Api\SafeZone.Modules.Incident.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\SafeZone.Modules.Notifications.Api\SafeZone.Modules.Notifications.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Media\SafeZone.Modules.Media.Api\SafeZone.Modules.Media.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Organization\SafeZone.Modules.Organization.Api\SafeZone.Modules.Organization.Api.csproj" />
    <ProjectReference Include="..\..\Modules\Payments\SafeZone.Modules.Payments.Api\SafeZone.Modules.Payments.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>





